server:
  port: 8761
#server.port=8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
#eureka.server.enable-self-preservation=false