
DROP TABLE REIMBURSE;
DROP TABLE EMPLOYEE;


DROP SEQUENCE REIMBURSEID_SEQ;
DROP SEQUENCE EMPID_SEQ;

DROP TRIGGER EMPID_TR;
DROP TRIGGER REIMBURSEID_TR;


CREATE TABLE EMPLOYEE  (
    EMP_ID NUMBER(5) PRIMARY KEY,
    EMP_NAME VARCHAR2(25) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    USER_PASS VARCHAR2(50) NOT NULL,
    REPORT_TO NUMBER(5),
    BIRTH_DATE DATE,
    URL VARCHAR2(250)  
    )
/
CREATE TABLE REIMBURSE(
    REIMBURSE_ID NUMBER(5) CONSTRAINT PK_REQUESTNO PRIMARY KEY,
    REQUEST_BY NUMBER(5) CONSTRAINT FK_REQUESTBY REFERENCES EMPLOYEE(EMP_ID)
    ON DELETE SET NULL,
    AMOUNT DOUBLE PRECISION,
    APPROVE_BY NUMBER(5),
    DATE_REQUEST DATE,
    DATE_APPROVE DATE,
    STATUS VARCHAR2(10),
    DESCRIPTION VARCHAR2(500),
    URL VARCHAR2(250)
    )
/    
CREATE SEQUENCE EMPID_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 3;
/
CREATE SEQUENCE REIMBURSEID_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 3;
/

CREATE OR REPLACE TRIGGER EMPID_TR
    BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW
BEGIN
  SELECT EMPID_SEQ.NEXTVAL INTO :NEW.EMP_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER REIMBURSEID_TR
    BEFORE INSERT ON REIMBURSE
    FOR EACH ROW
BEGIN
    SELECT REIMBURSEID_SEQ.NEXTVAL INTO :NEW.REIMBURSE_ID FROM DUAL;
END;
/
INSERT INTO EMPLOYEE(EMP_NAME, USER_NAME, USER_PASS, REPORT_TO, BIRTH_DATE, URL)
    VALUES('Dustin Harbor', 'dustin123', '123', 1, DATE '1980-12-01', 'https://randomuser.me/api/portraits/men/10.jpg');
    
INSERT INTO EMPLOYEE(EMP_NAME, USER_NAME, USER_PASS, REPORT_TO, BIRTH_DATE, URL)
    VALUES('Bonon Jackson', 'bonon', '123', 1, DATE '1971-10-01', 'https://randomuser.me/api/portraits/men/11.jpg');
    
INSERT INTO EMPLOYEE(EMP_NAME, USER_NAME, USER_PASS, REPORT_TO, BIRTH_DATE, URL)
    VALUES('Justin Bine', 'justin', '123', 1, DATE '1982-02-01', 'https://randomuser.me/api/portraits/men/12.jpg');
    
INSERT INTO EMPLOYEE(EMP_NAME, USER_NAME, USER_PASS, REPORT_TO, BIRTH_DATE, URL)
    VALUES('Jackson Wield', 'jackson', '123', 2, DATE '1980-12-01', 'https://randomuser.me/api/portraits/women/49.jpg');
    
INSERT INTO EMPLOYEE(EMP_NAME, USER_NAME, USER_PASS, REPORT_TO, BIRTH_DATE, URL)
    VALUES('Michael Jackson', 'michael', '123', 3, DATE '1979-10-01', 'https://randomuser.me/api/portraits/women/39.jpg');
    
INSERT INTO EMPLOYEE(EMP_NAME, USER_NAME, USER_PASS, REPORT_TO, BIRTH_DATE, URL)
    VALUES('Dustin Bean', 'dustin', '123', 2, DATE '1989-02-01', 'https://randomuser.me/api/portraits/women/29.jpg');
/    
    
    
    
INSERT INTO REIMBURSE(REQUEST_BY, AMOUNT, APPROVE_BY, DATE_REQUEST, DATE_APPROVE, STATUS, DESCRIPTION, URL)
    VALUES(5, 3.56, 3, DATE '1990-02-01',  DATE '2018-02-02', 'Approved', 'Movies with managers', 'wwww.twitter.com');   
    
INSERT INTO REIMBURSE(REQUEST_BY, AMOUNT, APPROVE_BY, DATE_REQUEST, DATE_APPROVE, STATUS, DESCRIPTION, URL)
    VALUES(6, 45.56, 2, DATE '1980-02-01',  DATE '2018-02-02', 'Approved', 'Shampoo at Cops Box', 'wwww.twitter.com');   
    
INSERT INTO REIMBURSE(REQUEST_BY, AMOUNT, APPROVE_BY, DATE_REQUEST, DATE_APPROVE, STATUS, DESCRIPTION, URL)
    VALUES(4, 71.56, 2, DATE '1987-02-01',  DATE '2018-02-02', 'Denied', 'Hotel at Paris', 'wwww.twitter.com');   
    
    
INSERT INTO REIMBURSE(REQUEST_BY, AMOUNT, APPROVE_BY, DATE_REQUEST, DATE_APPROVE, STATUS, DESCRIPTION, URL)
    VALUES(3, 23.56, 1, DATE '1966-02-01',  DATE '2018-02-02', 'Approved', 'Travel to Japan', 'wwww.twitter.com');   
    
INSERT INTO REIMBURSE(REQUEST_BY, AMOUNT, APPROVE_BY, DATE_REQUEST, DATE_APPROVE, STATUS, DESCRIPTION, URL)
    VALUES(4, 83.56, 2, DATE '1949-02-01',  DATE '2018-02-02', 'Denied', 'Lunch with clients', 'wwww.twitter.com');   
    
    
INSERT INTO REIMBURSE(REQUEST_BY, AMOUNT, APPROVE_BY, DATE_REQUEST, DATE_APPROVE, STATUS, DESCRIPTION, URL)
    VALUES(5, 93.56, 2, DATE '1982-02-01',  DATE '2018-02-02', 'Denied', 'Java Courses and learning online', 'wwww.twitter.com');   
/    
    
COMMIT;
/    
    
    
select * from employee;

SELECT * FROM REIMBURSE;


describe employee;
    

    