ALTER TABLE REIMBURSEMENT
DROP CONSTRAINT FK_REIMBURSEMENT_EMPLOYEE;

ALTER TABLE REIMBURSEMENT
DROP CONSTRAINT FK_REIMBURSEMENT_MANAGER;

DROP TABLE EMPLOYEE;
DROP TABLE MANAGER;
DROP TABLE REIMBURSEMENT;
DROP SEQUENCE SQ_REIMBURSEMENT_PK;
/

CREATE TABLE EMPLOYEE (
    EMAIL VARCHAR2(40) CONSTRAINT PK_EMPLOYEE PRIMARY KEY,
    EMPLOYEE_PASSWORD VARCHAR2(400),
    FIRST_NAME VARCHAR2(40),
    LAST_NAME VARCHAR2(40),
    PHONE VARCHAR2(40),
    STREET_ADDRESS VARCHAR2(40),
    CITY VARCHAR2(40),
    STATE VARCHAR2(40),
    ZIP_CODE VARCHAR2(40)
);
/

CREATE TABLE MANAGER (
    EMAIL VARCHAR2(40) CONSTRAINT PK_MANAGER PRIMARY KEY,
    MANAGER_PASSWORD VARCHAR2(400) NOT NULL
);
/

CREATE TABLE REIMBURSEMENT (
    REIMBURSEMENT_ID NUMBER(20) CONSTRAINT PK_ACCOUNT PRIMARY KEY,
    STATUS VARCHAR2(20) DEFAULT 'Pending',
    RESOLVED_BY VARCHAR2(40),
    REQUESTED_BY VARCHAR2(40),
    REASON VARCHAR2(200),
    OUTCOME VARCHAR2(20),
    AMOUNT VARCHAR2(20),
    S3KEY VARCHAR(200),
    INSERTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
/

CREATE SEQUENCE SQ_REIMBURSEMENT_PK
START WITH 1
INCREMENT BY 1;    
/

CREATE OR REPLACE TRIGGER TR_INSERT_REIMBURSEMENT
BEFORE INSERT ON REIMBURSEMENT
FOR EACH ROW
BEGIN
    SELECT SQ_REIMBURSEMENT_PK.NEXTVAL INTO :NEW.REIMBURSEMENT_ID FROM DUAL;
END;
/

ALTER TABLE REIMBURSEMENT
ADD CONSTRAINT FK_REIMBURSEMENT_EMPLOYEE
FOREIGN KEY (REQUESTED_BY) REFERENCES EMPLOYEE(EMAIL) ON DELETE CASCADE;
/

ALTER TABLE REIMBURSEMENT
ADD CONSTRAINT FK_REIMBURSEMENT_MANAGER
FOREIGN KEY (RESOLVED_BY) REFERENCES MANAGER(EMAIL) ON DELETE CASCADE;
/

INSERT INTO MANAGER VALUES('nick.costigan@gmail.com', '$2a$10$UoN1BeeYXiuBPKtefJ8Qx.pS2ekynBPtLjAD.aovk/qFTI3tBlq0y');
INSERT INTO EMPLOYEE VALUES('bob.revature@gmail.com', '$2a$10$UoN1BeeYXiuBPKtefJ8Qx.iPz9GVRYmhFqVQlxo4LS/.eIS7PeykG', 'Bob', 'Rounds', '(401)555-5555', '125 Main Street', 'North Scituate', 'RI', '02857');
COMMIT;