--Drops in case I need to restart randomly
DROP TABLE EMPLOYEE;
DROP TABLE REIMBURSMENT;
DROP TABLE RTYPES;
DROP TABLE RSTATES;

--Tables being created
CREATE TABLE EMPLOYEE(
    E_ID NUMBER(5) CONSTRAINT PK_EM PRIMARY KEY,
    EMP_NAME VARCHAR2(50),
    E_TYPE VARCHAR2(25),
    E_USERNAME VARCHAR2(25),
    E_PASSWORD VARCHAR(20),
    E_POSITION VARCHAR(20)
);

--Going to only have the 3 states: Pending, Denied, Approved
CREATE TABLE RSTATES(
    STATE_NUMBER NUMBER(2) CONSTRAINT PK_R PRIMARY KEY,
    STATE_NAME VARCHAR2(10)
);

--All three commented out here at no point will I need more hopefully...
--INSERT INTO RSTATES (STATE_NUMBER,STATE_NAME) VALUES (1,'Pending');
--INSERT INTO RSTATES (STATE_NUMBER,STATE_NAME) VALUES (2,'Denied');
--INSERT INTO RSTATES (STATE_NUMBER,STATE_NAME) VALUES (3,'Approved');


--Table that holds the types of reimbursement request you can make 
CREATE TABLE RTYPES(
    TYPE_ID NUMBER(2) CONSTRAINT PK_TYPE PRIMARY KEY,
    TYPE_NAME VARCHAR2(30)
);

--Default Types already inserted
INSERT INTO RTYPES (TYPE_ID,TYPE_NAME) VALUES (1,'Training');
INSERT INTO RTYPES (TYPE_ID,TYPE_NAME) VALUES (2,'Food');
INSERT INTO RTYPES (TYPE_ID,TYPE_NAME) VALUES (3,'Travel');
INSERT INTO RTYPES (TYPE_ID,TYPE_NAME) VALUES (4,'Medical');
INSERT INTO RTYPES (TYPE_ID,TYPE_NAME) VALUES (5,'Other');


CREATE TABLE REIMBURSEMENT(
    R_ID NUMBER(8) CONSTRAINT PK_REIM PRIMARY KEY,
    MODIFIER_ID NUMBER(5),
    AMOUNT NUMBER(6),
    REASON VARCHAR2(800),
    DATE_MADE DATE,
    DATE_MODI DATE,
    STATE_NUMBER NUMBER(1) CONSTRAINT FK_REIM_STATE REFERENCES RSTATES,
    E_ID NUMBER(5) CONSTRAINT FK_EMP_ID REFERENCES EMPLOYEE,
    TYPE_ID NUMBER(2) CONSTRAINT FK_TYPE_ID REFERENCES RTYPES
);

--ONLY need the 2 increments for those primary keys in the RTYPES and EMPLOYEE table
CREATE SEQUENCE SQ_EMP_ID
START WITH 10 INCREMENT BY 5;

CREATE SEQUENCE SQ_RI_ID
START WITH 346 INCREMENT BY 551;

CREATE OR REPLACE TRIGGER TR_INSERT_EMPLOYEE
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_EMP_ID.NEXTVAL INTO :NEW.E_ID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TR_INSERT_REIMBURSE
BEFORE INSERT ON REIMBURSEMENT
FOR EACH ROW
BEGIN
    SELECT SQ_RI_ID.NEXTVAL INTO :NEW.R_ID FROM DUAL;
END;

INSERT INTO REIMBURSEMENT (MODIFIER_ID, AMOUNT, REASON, DATE_MADE, DATE_MODI, STATE_NUMBER, E_ID, TYPE_ID) VALUES (25, 1000, 'Soothed 30 more sandwiches than originally informed to sooth', DATE '2017-12-21', DATE '2018-02-12', 2,15,5);
INSERT INTO EMPLOYEE (EMP_NAME, E_TYPE, E_USERNAME, E_PASSWORD, E_POSITION) VALUES ('Jeffery Montgomery', 'Manager','Jmont','pass11!','Motivational Yeller');
INSERT INTO EMPLOYEE (EMP_NAME, E_TYPE, E_USERNAME, E_PASSWORD, E_POSITION) VALUES ('Malcom Hayward', 'Manager','Hway','pares2','Mean Yeller');
INSERT INTO EMPLOYEE (EMP_NAME, E_TYPE, E_USERNAME, E_PASSWORD, E_POSITION) VALUES ('Ja Ruler', 'Regular','JaRuled','Babbbyyy','Positive Influence');

SELECT * FROM EMPLOYEE WHERE E_TYPE = 'Manager';

COMMIT;