DROP TABLE ERS_REIMBURSEMENT;
DROP TABLE ERS_EMPLOYEE;
DROP SEQUENCE SQ_ERS_EMPLOYEE_PK;
DROP SEQUENCE SQ_ERS_REIMBURSEMENT_PK;

CREATE TABLE ERS_EMPLOYEE(
    EMPLOYEE_ID NUMBER(6),
    EMPLOYEE_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(60) NOT NULL UNIQUE,
    PASSWORD VARCHAR(20) NOT NULL,
    MANAGER_ID NUMBER(6)
);

ALTER TABLE ERS_EMPLOYEE
ADD CONSTRAINT PK_ERS_EMPLOYEE
PRIMARY KEY (EMPLOYEE_ID);

ALTER TABLE ERS_EMPLOYEE
ADD CONSTRAINT FK_ERS_EMPLOYEE_MANAGER
FOREIGN KEY (MANAGER_ID)
REFERENCES ERS_EMPLOYEE (EMPLOYEE_ID)
ON DELETE CASCADE;

CREATE SEQUENCE SQ_ERS_EMPLOYEE_PK
START WITH 1;

CREATE OR REPLACE TRIGGER TR_ERS_EMPLOYEE_PK
BEFORE INSERT ON ERS_EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_ERS_EMPLOYEE_PK.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;

/

CREATE TABLE ERS_REIMBURSEMENT(
    REIMBURSEMENT_ID NUMBER(10),
    REIMBURSEMENT_NAME VARCHAR2(60),
    DESCRIPTION VARCHAR2(1000),
    AMOUNT NUMBER(7,2) NOT NULL,
    STATUS NUMBER(1,0) DEFAULT 0,
    EMPLOYEE_ID NUMBER(6) NOT NULL,
    PICTURE BLOB
    );
    
ALTER TABLE ERS_REIMBURSEMENT
ADD CONSTRAINT PK_ERS_REIMBURSEMENT
PRIMARY KEY (REIMBURSEMENT_ID);

ALTER TABLE ERS_REIMBURSEMENT
ADD CONSTRAINT FK_ERS_REIMBURSEMENT_EMPLOYEE
FOREIGN KEY (EMPLOYEE_ID)
REFERENCES ERS_EMPLOYEE
ON DELETE CASCADE;

CREATE SEQUENCE SQ_ERS_REIMBURSEMENT_PK
START WITH 1;

CREATE OR REPLACE TRIGGER TR_ERS_REIMBURSEMENT_PK
BEFORE INSERT ON ERS_REIMBURSEMENT
FOR EACH ROW
BEGIN
    SELECT SQ_ERS_REIMBURSEMENT_PK.NEXTVAL INTO :NEW.REIMBURSEMENT_ID FROM DUAL;
END;
/

INSERT INTO ERS_EMPLOYEE (EMPLOYEE_NAME, EMAIL,PASSWORD) VALUES('Holly Lane','holly.reimbursements@gmail.com','password');
INSERT INTO ERS_EMPLOYEE (EMPLOYEE_NAME, EMAIL,PASSWORD,MANAGER_ID) VALUES('Jeffrey Terrasse','insert@java.com','password',1);
INSERT INTO ERS_EMPLOYEE (EMPLOYEE_NAME, EMAIL,PASSWORD,MANAGER_ID) VALUES('Aiden Costa','delete@java.com','password',2);
INSERT INTO ERS_EMPLOYEE (EMPLOYEE_NAME, EMAIL,PASSWORD,MANAGER_ID) VALUES('Kate Rhodes','query@java.com','password',1);
INSERT INTO ERS_EMPLOYEE (EMPLOYEE_NAME, EMAIL,PASSWORD,MANAGER_ID) VALUES('Rolf Girard','update@java.com','password',1);
INSERT INTO ERS_EMPLOYEE (EMPLOYEE_NAME, EMAIL,PASSWORD,MANAGER_ID) VALUES('Noelia Madsen','group@java.com','password',2);


INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('Plastic forks',7,2,'Running low on utensils');
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('Pizza',43,2,'Birthday party for Rolf');
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('Cleaning supplies',10,4,'Cleaning up after the birthday party');
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('New printer',200,2,'Old printer broke');
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('Mop',12,2,'Someone duct taped a leak on Friday, but the pressure built up and sprayed water all over the break room');
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('Plumber',520,2,'Burst pipe');
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('Carpet',1200,4,'Carpet ruined, need to buy a new one');
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('Installing carpet',400,4,'Installing carpet');
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('Electrician for re-wiring',432.50,2,'Carpet installation accidentally ripped out wiring');
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('Flashlights',25,2,'To see while the power is out');
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('New ballpoint pen',40,5,'My pen got ruined by a leak');
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('Printer paper',22,3,'Running low on paper');
COMMIT;
INSERT INTO ERS_EMPLOYEE (EMPLOYEE_NAME, EMAIL,PASSWORD,MANAGER_ID) VALUES('Billy','reimbursementemployee@gmail.com','password',1);
INSERT INTO ERS_REIMBURSEMENT (REIMBURSEMENT_NAME,AMOUNT,EMPLOYEE_ID,DESCRIPTION) VALUES('Water filter',40.4,5,'Need new filter');
COMMIT;