CREATE TABLE BANK_LINK(
    USERNAME VARCHAR2(50) CONSTRAINT FK_USER_NAME REFERENCES BANK_USER,
    ACCOUNT_ID NUMBER(9) CONSTRAINT FK_ACT_ID REFERENCES BANK_ACCOUNT,
    CONSTRAINT PK_BANK_LINK PRIMARY KEY (USERNAME, ACCOUNT_ID)
);

CREATE TABLE BANK_USER(
    USERNAME VARCHAR2(50) CONSTRAINT PK_USER PRIMARY KEY,
    PASSWORD VARCHAR2(128)
);

CREATE TABLE BANK_ACCOUNT(
    ACCOUNT_ID NUMBER(9) CONSTRAINT PK_BNK_ACT PRIMARY KEY,
    BALANCE NUMBER(7,2),
    NICKNAME VARCHAR2(50)
);

CREATE TABLE BANK_TRANSACTION(
    TYPE VARCHAR2(100) CONSTRAINT PK_TRAN PRIMARY KEY,
    ACCOUNT_ID NUMBER(9) CONSTRAINT FK_BNK_TRAN REFERENCES BANK_ACCOUNT, 
    USERNAME VARCHAR2(50),
    AMOUNT NUMBER(7,2),
    BALANCE NUMBER(7,2),
    DATE_MADE DATE,
    OTHER_ACCOUNT_ID VARCHAR2(9)
);

SELECT * FROM BANK_USER;
