DROP TABLE ERS_EMPLOYEE;
DROP TABLE ERS_REQUEST;



CREATE TABLE ERS_EMPLOYEE (
    EMPL_ID NUMBER(5) CONSTRAINT PK_EMPLOYEE PRIMARY KEY,
    FIRSTNAME VARCHAR2(20) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    PICTURE BLOB,
    EMAIL VARCHAR(50) NOT NULL,
    PWD VARCHAR(30) NOT NULL,
    JOB_TITLE VARCHAR(20),
    DEPARTMENT VARCHAR(20)
);

CREATE TABLE ERS_REQUEST (
    REQ_ID NUMBER(7) CONSTRAINT PK_REQUEST PRIMARY KEY,
    EMPL_ID NUMBER(5) NOT NULL,
    AMOUNT NUMBER(5) DEFAULT 0,
    DESCRIPTION VARCHAR(100),
    STATUS VARCHAR(15),
    DATE_REQUESTED DATE,
    DATE_RESOLVED DATE    
);
ALTER TABLE ERS_REQUEST
ADD CONSTRAINT FK_EMPLOYEE_REQUEST
FOREIGN KEY (EMPL_ID) REFERENCES ERS_EMPLOYEE ON DELETE CASCADE;
