DROP SEQUENCE ERS_EMP_PK;
DROP SEQUENCE ERS_REQ_PK;
DROP TABLE ERS_REQUEST;
DROP TABLE ERS_EMPLOYEE;



CREATE TABLE ERS_EMPLOYEE (
    EMPL_ID NUMBER(5) CONSTRAINT PK_EMPLOYEE PRIMARY KEY,
    FIRSTNAME VARCHAR2(20) NOT NULL,
    LASTNAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    PWD VARCHAR2(30) NOT NULL,
    MANAGER_ID NUMBER(5),
    PICTURE BLOB
);
/

CREATE TABLE ERS_REQUEST (
    REQ_ID NUMBER(7) CONSTRAINT PK_REQUEST PRIMARY KEY,
    EMPL_ID NUMBER(5) NOT NULL,
    AMOUNT NUMBER(7,2) DEFAULT 0,
    DESCRIPTION VARCHAR2(100),
    STATUS VARCHAR2(15),
    DATE_REQUESTED DATE,
    DATE_RESOLVED DATE,    
    RESOLVED_BY VARCHAR(40)
);
/

ALTER TABLE ERS_REQUEST
ADD CONSTRAINT FK_EMPLOYEE_REQUEST
FOREIGN KEY (EMPL_ID) REFERENCES ERS_EMPLOYEE ON DELETE CASCADE;
/

CREATE SEQUENCE ERS_EMP_PK 
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE ERS_REQ_PK
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER ERS_INSERT_EMP 
BEFORE INSERT ON ERS_EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT ERS_EMP_PK.NEXTVAL INTO :NEW.EMPL_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER ERS_INSERT_REQ
BEFORE INSERT ON ERS_REQUEST
FOR EACH ROW
BEGIN
    SELECT ERS_REQ_PK.NEXTVAL INTO :NEW.REQ_ID FROM DUAL;
END;
/


INSERT INTO ERS_EMPLOYEE (FIRSTNAME, LASTNAME, EMAIL, PWD) VALUES ('AD', 'MIN', 'ADMIN@EXAMPLE.COM', 'pwd');
SELECT * FROM ERS_EMPLOYEE;


COMMIT;